CREATE TABLE `agendamentos` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` INT UNSIGNED NOT NULL,
	`data` DATE NOT NULL,
	`hora` TIME NOT NULL,
	`created_at` TIMESTAMP NOT NULL DEFAULT (now()),
	`modified_at` TIMESTAMP NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;