const ERRORS = {
    // ERROS DE AGENDAMENTO
    TIME_CONFLICT: "TIME_CONFLICT",
    INVALID_DATA: "INVALID_DATA",
    NO_APPOINTMENTS: "NO_APPOINTMENTS",

    //ERROS DE LOGIN/REGISTER/AUTH
    USER_NOT_FOUND: "USER_NOT_FOUND",
    INVALID_LOGIN: "INVALID_LOGIN",

    //INTERNAL SERVER ERROR
    INTERNAL_ERROR: "INTERNAL_ERROR"
}

module.exports = ERRORS